services:
  - type: web
    name: yt-fake-detector-api
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
